### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Yoccoi** [Yoccoi/furima-29686#9]
# URL
https://furima-29686.herokuapp.com/

# Basic認証のIDとパスワード
ID: admin
パスワード: 2222

# 出品者用のメールアドレスとパスワード
メールアドレス: test@test
パスワード: "aaaaa0"

# 購入者用のメールアドレスとパスワード
メールアドレス: test@tarou
パスワード: "aaaaa0"

# 購入用カードの番号・期限・セキュリティコード
番号: 4242424242424242
期限: 03 / 25
セキュリティコード: 123

**Comment by sho0127** [comment]
Yoccoiさん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**

**Comment by Yoccoi** [comment]
LGTMありがとうございます！！
それでは、引き続き追加実装を頑張っていきます！
改めまして挙動確認ありがとうございました！
